### PR TITLE
Addition of setCodePage(uint8_t page) function

### PR DESCRIPTION
**Pull request by altishchenko**
Ability to switch between character code pages on certain models of the LCDs.

### CODE REVIEW

**Comment by ajvdw** [comment]
Hi,

I've encountered problems in timing with a number of arduino's (mostly megas) combined with a LCD2004. By changing the pulse_enable timing, I've solved these issues. The cause was the 1ms wait that turned out to be less the 450ns in some cases.

My solution:

void LiquidCrystal::pulseEnable() {
  // Due to inaccurate timing, skipping pulses. Results scrambled screen 
  // (http://arduino.cc/en/Reference/delayMicroseconds)
  digitalWrite(_enable_pin, LOW);
  delayMicroseconds(5);    
  digitalWrite(_enable_pin, HIGH);
  delayMicroseconds(5);  
  digitalWrite(_enable_pin, LOW);
  delayMicroseconds(90);   // commands need > 37us to settle, used to 100
}

**Comment by altishchenko** [comment]
ajvdw,
This is expected as per the link you referencing:
> This function works very accurately in the range 3 microseconds and up.
So 1 is not a proper value :)

**Comment by altishchenko** [comment]
To the mergers - sorry to notice that too late, but the last commit introduced some whitespace cleanup along the actual changes... Mea culpa!

**Comment by altishchenko** [comment]
Stability issues with delay(50). Will come back when resolved.

**Pull request closed without merging**
